### ISSUE TITLE
Example from STEP-by-STEP guide not working

### ISSUE THREAD

**Issue by dsyer** [CRaC/docs#1] opened 2022-12-20 14:41 UTC
I ran it from the source code at https://github.com/CRaC/example-jetty. Also lifted the CLI stuff from the Github action there. The checkpoint restore seems to fail:

```
$ java -XX:CRaCCheckpointTo=cr -XX:+UnlockDiagnosticVMOptions -XX:+CRTraceStartupTime -Djdk.crac.trace-startup-time=true -jar target/example-jetty-1.0-SNAPSHOT.jar 
2022-12-20 14:32:11.770:INFO::main: Logging initialized @1090ms to org.eclipse.jetty.util.log.StdErrLog
2022-12-20 14:32:11.828:INFO:oejs.Server:main: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 17-crac+3-15
2022-12-20 14:32:11.872:INFO:oejs.AbstractConnector:main: Started ServerConnector@782830e{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-12-20 14:32:11.875:INFO:oejs.Server:main: Started @1205ms
```

When `jcmd` is executed:

```
2022-12-20 14:33:20.147:INFO:oejs.AbstractConnector:Thread-9: Stopped ServerConnector@782830e{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
CR: Checkpoint ...
STARTUPTIME 1830138185665851 restore-native
JVM: invalid info for restore provided (may be failed checkpoint)
STARTUPTIME 1830138187472970 restore
2022-12-20 14:33:21.211:INFO:oejs.Server:Thread-9: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 17-crac+3-15
2022-12-20 14:33:21.219:INFO:oejs.AbstractConnector:Thread-9: Started ServerConnector@782830e{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-12-20 14:33:21.220:INFO:oejs.Server:Thread-9: Started @70549ms
STARTUPTIME 1830138197994477 restore-finish
```

The same thing happens with other versions of Jetty (I tried 11.0.12 as well).

**Comment by AntonKozlov** [comment] 2022-12-20 16:44
Could you post dump4.log from your `cr/`? It should have some additional debugging info

**Comment by dsyer** [comment] 2022-12-20 17:34
[dump4.log](https://github.com/CRaC/docs/files/10270836/dump4.log)

**Comment by dsyer** [comment] 2022-12-21 09:09
I found that it works if you run the app initially (`java -XX:CRaCCheckpointTo=cr`) and `jcmd` as root. It doesn't work if either process is running as non-root. You can, however, `chown` the `cr` directory and its contents and then run `java -XX:CRaCRestoreFrom=cr` as non-root.

Kind of sucks if that's actually a limitation of CRaC. I don't think I want to be doing any demos if I have to be root.

**Comment by AntonKozlov** [comment] 2022-12-21 11:32
That's indeed true. Could you check have you extracted CRaC JDK with `sudo tar ...` as advised  in https://github.com/CRaC/docs/#jdk? I expect that should allow checkpoint to be done by a regular user.

**Comment by AntonKozlov** [comment] 2022-12-21 13:55
Yes, that's correct, we are asking "sudo tar" to keep permissions and SUID bit on criu, thank you for trying. Could you explain a bit about the environment? Is it a container? Is it on a Linux system or something like WSL or Docker-on-Mac?

**Comment by dsyer** [comment] 2022-12-21 14:22
Plain Linux

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by dsyer** [comment] 2022-12-21 18:01
UPDATE: I tried in a container (`mcr.microsoft.com/devcontainers/java:0-17`) and that worked (as long as I started with `--privileged`). So what is it about my physical machine that criu doesn't like?

**Comment by AntonKozlov** [comment] 2022-12-21 19:45
Very strange, containers are usually more restricted, at least inheriting kernel settings from the host system. Your dump4.log has very small numbers as PIDs, that’s why I assumed it was a container. And the issue still the same?.. I’m setting a VM with the ubuntu to check that

**Comment by AntonKozlov** [comment] 2022-12-22 13:33
Hmm, it worked on my Vagrant VM
```
vagrant@ubuntu-jammy:~$ ./jdk17-crac+2/bin/java -XX:CRaCCheckpointTo=./cr Test.java
CR: Checkpoint ...
Killed
vagrant@ubuntu-jammy:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

Java PID number although is not that small (from dump4.log)
```
(00.508641) Dumping pstree (pid: 1663320)
(00.508642) ----------------------------------------
(00.508644) Process: 1663320(1663320)
(00.508655) ----------------------------------------
```

**Comment by dsyer** [comment] 2022-12-23 10:28
OK, here's a clue: that file that can't be "ghosted" (`/dev/shm/.org.chromium.Chromium.lzU6n7`) was created and deleted by VSCode. I get that error when I run the CRaC demo in a terminal in VSCode. If I shut down the IDE and run in a normal terminal, it all works as expected. Is there anything else I can do to work around or push this closer to diagnosing the actual problem?

**Comment by AntonKozlov** [comment] 2022-12-27 18:06
Interestingly, that "ghosted" file should have appeared in the dump4.log and been pointed as the root cause. How did you find that file to be a problem?

It looks like the bug is actually in CRaC not reporting the SHM properly in the first place. I think the correct behavior would be to refuse checkpoint, as it's unclear for JVM what that SHM is for, and restore may fail if the file is missing, as it will likely be. Does it sound legit? At least this should save some time debugging.

**Comment by dsyer** [comment] 2022-12-27 21:39
> How did you find that file to be a problem?

it was in the dump file. Right at the end when it reported an error.

I don’t really understand what happened, but why would the parent process of the one that runs the app need to be checkpointed at this level?

**Comment by AntonKozlov** [comment] 2022-12-29 15:05
Oh, sorry, my bad, I looked at a wrong dump4.log all the time :(

Thanks for the hint with VSCode, turns out it provides a lot of open file descriptors for the java process. And we treat all file descriptors that exist before JVM initialization as ones that will be there forever. However, even if the checkpoint would succeed, we'd be able to restore only under VSCode, likely the same instance only. So I think JVM should process file descriptors provided by the environment in some better way than blindly assume they are OK.

E.g. just for the shell running under VSCode:

```
anton@mercury:~$ ls -la /proc/$$/fd/
total 0
dr-x------ 2 anton users  0 Dec 29 16:23 .
dr-xr-xr-x 9 anton users  0 Dec 29 16:22 ..
lrwx------ 1 anton users 64 Dec 29 16:23 0 -> /dev/pts/38
lrwx------ 1 anton users 64 Dec 29 16:23 1 -> /dev/pts/38
lr-x------ 1 anton users 64 Dec 29 16:23 103 -> /usr/lib/electron19/v8_context_snapshot.bin
lr-x------ 1 anton users 64 Dec 29 16:23 12 -> /usr/lib/electron19/v8_context_snapshot.bin
lrwx------ 1 anton users 64 Dec 29 16:23 2 -> /dev/pts/38
lrwx------ 1 anton users 64 Dec 29 16:23 255 -> /dev/pts/38
lrwx------ 1 anton users 64 Dec 29 16:23 28 -> 'socket:[10159179]'
lrwx------ 1 anton users 64 Dec 29 16:23 29 -> '/tmp/.org.chromium.Chromium.n4fmVM (deleted)'
lr-x------ 1 anton users 64 Dec 29 16:23 30 -> /usr/share/fonts/liberation/LiberationSerif-Regular.ttf
lr-x------ 1 anton users 64 Dec 29 16:23 31 -> '/home/anton/.config/Code - OSS/Dictionaries/en-US-10-1.bdic'
lr-x------ 1 anton users 64 Dec 29 16:23 32 -> /proc/2663681/statm
lr-x------ 1 anton users 64 Dec 29 16:23 33 -> /proc/2663681/status
lrwx------ 1 anton users 64 Dec 29 16:23 38 -> 'socket:[10144760]'
lrwx------ 1 anton users 64 Dec 29 16:23 39 -> '/dev/shm/.org.chromium.Chromium.yA5xvp (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 40 -> '/dev/shm/.org.chromium.Chromium.w884a1 (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 41 -> '/dev/shm/.org.chromium.Chromium.r17XPx (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 42 -> '/dev/shm/.org.chromium.Chromium.BLv0fa (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 43 -> '/dev/shm/.org.chromium.Chromium.qABDoy (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 44 -> '/dev/shm/.org.chromium.Chromium.191pKQ (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 45 -> '/dev/shm/.org.chromium.Chromium.XiEgFo (deleted)'
lrwx------ 1 anton users 64 Dec 29 16:23 46 -> '/dev/shm/.org.chromium.Chromium.7QumcE (deleted)'
lr-x------ 1 anton users 64 Dec 29 16:23 48 -> /usr/lib/code/node_modules.asar
l-wx------ 1 anton users 64 Dec 29 16:23 49 -> '/home/anton/.config/Code - OSS/logs/20221229T162222/ptyhost.log'
lr-x------ 1 anton users 64 Dec 29 16:23 50 -> /usr/lib/code/node_modules.asar
```

**Comment by AntonKozlov** [comment] 2023-03-02 17:55
Hi, we have made a change to handle this problem: https://github.com/openjdk/crac/pull/45.

That is not a part of any EA build, but it's possible to try that in a perliminary build with that change https://github.com/AntonKozlov/openjdk-builds/actions/runs/4303926123. This build will be there for a while, until GHA retention policies clean that. The change is also planned for a future EA builds.

I've tested the preliminary build in the VSCode terminal and it has worked. 

Thank you for the report!

**Comment by tzolov** [comment] 2023-03-22 15:37
Hi @AntonKozlov , 
Just stumbled on the same issue while using the VS Code terminal.  I'm running:
```
java --version
openjdk 17-crac 2021-09-14
OpenJDK Runtime Environment (build 17-crac+4-17)
OpenJDK 64-Bit Server VM (build 17-crac+4-17, mixed mode, sharing)
```
Is the above fix supposed to be inside?

**Comment by AntonKozlov** [comment] 2023-03-24 17:36
Hi @tzolov,

Not in that build.

The fix is in the next build: https://github.com/CRaC/openjdk-builds/releases/tag/17-crac%2B5

**Comment by AntonKozlov** [comment] 2023-04-25 15:41
Closing as resolved, should work in jdk17-crac+5. Please feel free to reopen if something goes wrong.

**Closed by AntonKozlov** 2023-04-25 15:41 UTC
